name: AlarmClock CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Lab4/MySolution.sln

      - name: Build
        run: dotnet build Lab4/MySolution.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Lab4/MySolution.sln --no-build --verbosity normal --configuration Release