name: Docker Python CI

on:
  push:
    branches:
      - lab6
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Lab6/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mpt-lab6:latest
            ghcr.io/${{ github.repository_owner }}/mpt-lab6:${{ github.sha }}

  test-in-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/mpt-lab6:latest

      - name: Run tests inside container
        run: |
          docker run --rm \
            ghcr.io/${{ github.repository_owner }}/mpt-lab6:latest \
            pytest test_app.py
